### ISSUE TITLE
Support Nest Temperature Sensor

### ISSUE THREAD

**Issue by wtip** [dmegyesi/nest-prometheus#1]
The exporter does not report the temperature of the additional Nest Temperature Sensor.
It would be nice if all attached Nest Temperature Sensors were reported.

**Comment by wtip** [comment]
Feel free to close this. Sounds like the API doesn't support this at the moment at least https://github.com/jkoelker/python-nest/issues/164

**Comment by dmegyesi** [comment]
Sad to see this. Thank you for the heads up. Feel free to reopen when they release the new API.
